// app/(tabs)/features/group-purchasing/CampaignDetail/CampaignDetail.styles.js

import { StyleSheet } from "react-native";
import { SHADOWS } from "../../../../utils/group-purchasing/shadows";

export const campaignDetailStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8FAFC",
  },
  contentContainer: {
    paddingBottom: 30,
  },
  heroContainer: {
    position: "relative",
    height: 240,
    marginBottom: 20,
  },
  heroActions: {
    position: "absolute",
    top: 10,
    left: 16,
    right: 16,
    zIndex: 10,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  circleButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(255,255,255,0.95)",
    justifyContent: "center",
    alignItems: "center",
    ...SHADOWS.light,
  },
  imageContainer: {
    flex: 1,
    backgroundColor: "#FEF9F6",
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    justifyContent: "center",
    alignItems: "center",
  },
  verifiedOverlay: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(26, 92, 74, 0.9)",
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 100,
    marginTop: 12,
    gap: 6,
  },
  verifiedText: {
    fontSize: 12,
    fontFamily: "Nunito_600SemiBold",
    color: "#FFFFFF",
    fontWeight: "600",
    letterSpacing: 0.3,
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 18,
    marginHorizontal: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#F1F5F9",
    ...SHADOWS.card,
  },
  dealHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 8,
  },
  dealTitle: {
    fontSize: 20,
    fontWeight: "700",
    fontFamily: "Nunito_700Bold",
    color: "#1E293B",
    letterSpacing: -0.3,
    lineHeight: 26,
  },
  installerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 4,
    gap: 6,
  },
  installerName: {
    fontSize: 14,
    fontFamily: "Nunito_400Regular",
    color: "#64748B",
    fontWeight: "400",
  },
  priceContainer: {
    alignItems: "flex-end",
  },
  discountedPrice: {
    fontSize: 24,
    fontWeight: "800",
    fontFamily: "Nunito_700Bold",
    color: "#1A5C4A",
    letterSpacing: -0.5,
  },
  priceSubtext: {
    fontSize: 11,
    fontFamily: "Nunito_400Regular",
    color: "#94A3B8",
    fontWeight: "400",
    marginTop: 2,
  },
  regularPriceRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: "#F1F5F9",
  },
  regularPriceLabel: {
    fontSize: 13,
    fontFamily: "Nunito_400Regular",
    color: "#94A3B8",
    fontWeight: "400",
  },
  regularPrice: {
    fontSize: 14,
    fontFamily: "Nunito_400Regular",
    color: "#94A3B8",
    textDecorationLine: "line-through",
    fontWeight: "400",
  },
  progressHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  sectionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: "600",
    fontFamily: "Nunito_600SemiBold",
    color: "#1E293B",
  },
  progressCountContainer: {
    alignItems: "flex-end",
  },
  progressCount: {
    fontSize: 16,
    fontWeight: "700",
    fontFamily: "Nunito_700Bold",
    color: "#1E293B",
  },
  progressLabel: {
    fontSize: 11,
    fontFamily: "Nunito_400Regular",
    color: "#94A3B8",
    fontWeight: "400",
  },
  progressBarContainer: {
    marginBottom: 10,
  },
  progressBar: {
    height: 8,
    backgroundColor: "#E2E8F0",
    borderRadius: 100,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#1A5C4A",
    borderRadius: 100,
  },
  neededContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 4,
  },
  neededText: {
    fontSize: 13,
    fontFamily: "Nunito_400Regular",
    color: "#64748B",
    fontWeight: "400",
    lineHeight: 18,
  },
  fullTextContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 8,
    gap: 8,
  },
  fullText: {
    fontSize: 14,
    fontFamily: "Nunito_600SemiBold",
    color: "#10B981",
    fontWeight: "600",
  },
  organizerRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  heroImage: {
    width: "100%",
    height: "100%",
  },
  organizerAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#1A5C4A",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 14,
  },
  organizerAvatarText: {
    fontSize: 18,
    fontWeight: "600",
    fontFamily: "Nunito_700Bold",
    color: "#FFFFFF",
  },
  organizerInfo: {
    flex: 1,
  },
  organizerName: {
    fontSize: 15,
    fontWeight: "600",
    fontFamily: "Nunito_600SemiBold",
    color: "#1E293B",
  },
  organizerDateRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 2,
    gap: 6,
  },
  organizerDate: {
    fontSize: 13,
    fontFamily: "Nunito_400Regular",
    color: "#94A3B8",
  },
  messageButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F1F5F9",
    justifyContent: "center",
    alignItems: "center",
  },
  membersHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  memberRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
  },
  currentUserRow: {
    backgroundColor: "#F0FDF4",
    borderRadius: 8,
    paddingHorizontal: 10,
    marginHorizontal: -10,
    borderBottomWidth: 0,
  },
  newMemberRow: {},
  currentUserAvatar: {
    backgroundColor: "#1A5C4A",
  },
  currentUserAvatarText: {
    color: "#FFFFFF",
  },
  currentUserName: {
    fontWeight: "700",
    color: "#1A5C4A",
  },
  memberAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#E2E8F0",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  memberAvatarText: {
    fontSize: 13,
    fontWeight: "600",
    fontFamily: "Nunito_600SemiBold",
    color: "#475569",
  },
  memberName: {
    fontSize: 14,
    fontFamily: "Nunito_400Regular",
    color: "#1E293B",
    fontWeight: "500",
    flex: 1,
  },
  youBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1A5C4A",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    marginRight: 8,
    gap: 4,
  },
  youBadgeText: {
    fontSize: 10,
    fontFamily: "Nunito_600SemiBold",
    color: "#FFFFFF",
    fontWeight: "600",
  },
  memberStatusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 100,
  },
  memberStatusText: {
    fontSize: 11,
    fontFamily: "Nunito_600SemiBold",
    color: "#FFFFFF",
    fontWeight: "600",
    letterSpacing: 0.3,
  },
  emptyStateContainer: {
    alignItems: "center",
    paddingVertical: 20,
    gap: 8,
  },
  emptyMembersText: {
    fontSize: 14,
    fontFamily: "Nunito_400Regular",
    color: "#94A3B8",
    textAlign: "center",
  },
  joinButton: {
    backgroundColor: "#1A5C4A",
    paddingVertical: 16,
    borderRadius: 100,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 20,
    gap: 10,
    ...SHADOWS.button,
  },
  joinButtonDisabled: {
    backgroundColor: "#94A3B8",
    paddingVertical: 16,
    borderRadius: 100,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 20,
    gap: 10,
  },
  joinButtonText: {
    fontSize: 17,
    fontFamily: "Nunito_700Bold",
    color: "#FFFFFF",
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  alreadyJoinedContainer: {
    backgroundColor: "#E8F8F0",
    borderRadius: 16,
    padding: 20,
    alignItems: "center",
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 20,
    gap: 8,
  },
  alreadyJoinedText: {
    fontSize: 16,
    fontFamily: "Nunito_600SemiBold",
    color: "#10B981",
    fontWeight: "600",
  },
  viewDashboardButton: {
    backgroundColor: "#1A5C4A",
    paddingVertical: 12,
    paddingHorizontal: 28,
    borderRadius: 100,
    marginTop: 4,
  },
  viewDashboardButtonText: {
    fontSize: 15,
    fontFamily: "Nunito_600SemiBold",
    color: "#FFFFFF",
    fontWeight: "600",
  },
  errorText: {
    fontSize: 18,
    fontFamily: "Nunito_700Bold",
    color: "#EF4444",
    textAlign: "center",
    marginTop: 40,
    fontWeight: "500",
  },

  // ============================================================
  // ✅ NEW STYLES FOR ORGANIZER ACTIONS
  // ============================================================

  organizerBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1A5C4A",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    marginRight: 8,
    gap: 4,
  },
  organizerBadgeText: {
    fontSize: 10,
    fontFamily: "Nunito_600SemiBold",
    color: "#FFFFFF",
  },
  markPaidButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#10B981",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    gap: 4,
  },
  markPaidText: {
    fontSize: 10,
    fontFamily: "Nunito_600SemiBold",
    color: "#FFFFFF",
  },
  organizerSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  organizerSectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    fontFamily: "Nunito_600SemiBold",
    color: "#1E293B",
  },
  confirmButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1A5C4A",
    paddingVertical: 14,
    borderRadius: 100,
    gap: 8,
    marginBottom: 10,
    ...SHADOWS.button,
  },
  confirmButtonText: {
    fontSize: 16,
    fontFamily: "Nunito_600SemiBold",
    color: "#FFFFFF",
  },
  confirmDisabledContainer: {
    backgroundColor: "#F1F5F9",
    paddingVertical: 14,
    borderRadius: 100,
    alignItems: "center",
    marginBottom: 10,
  },
  confirmDisabledText: {
    fontSize: 14,
    fontFamily: "Nunito_400Regular",
    color: "#94A3B8",
  },
  shareButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F8FAFC",
    paddingVertical: 12,
    borderRadius: 100,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    gap: 8,
  },
  shareButtonText: {
    fontSize: 14,
    fontFamily: "Nunito_600SemiBold",
    color: "#1A5C4A",
  },
  leaveButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FEF2F2",
    paddingVertical: 14,
    borderRadius: 100,
    borderWidth: 1,
    borderColor: "#EF4444",
    gap: 8,
    marginBottom: 10,
    ...SHADOWS.button,
  },
  leaveButtonText: {
    fontSize: 16,
    fontFamily: "Nunito_600SemiBold",
    color: "#EF4444",
  },

  // app/(tabs)/features/group-purchasing/CampaignDetail/CampaignDetail.styles.js

  // Add these styles after the existing styles (around line 450, after the leaveButton styles)

  // ============================================================
  // ✅ MEMBER ACTIONS STYLES
  // ============================================================

  memberSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  memberSectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    fontFamily: "Nunito_600SemiBold",
    color: "#EF4444",
  },
  memberLeaveButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FEF2F2",
    paddingVertical: 14,
    borderRadius: 100,
    borderWidth: 1,
    borderColor: "#EF4444",
    gap: 8,
    ...SHADOWS.button,
  },
  memberLeaveButtonText: {
    fontSize: 16,
    fontFamily: "Nunito_600SemiBold",
    color: "#EF4444",
  },
});
